### ISSUE TITLE
Ability to clone a new project

### ISSUE THREAD

**Issue by BinyaminPekar** [uenz/SparkleShare#1] opened 2021-09-30 20:49 UTC
@uenz: could you, please check and confirm that your [SparkleShare-windows-nightly.msi](https://github.com/uenz/SparkleShare/releases/download/CI-Build/SparkleShare-windows-nightly.msi) can clone a new project? I was not able to clone my SparkleShare fork on GitHub. However I must admit that it could be due to me messing around with the old and new installation and the Windows' AppData folder... Thank you for the great PR!

**Comment by uenz** [comment] 2021-10-01 03:20
I´m sure that cloning repos and pushing / pulling files work with a locally built version. I´m also sure that pushing and pulling works with the installer version. So i (re)check that also cloning works with the installer, maybe there is an issue in the installer packet.

**Comment by uenz** [comment] 2021-10-01 14:54
Unfortunately i can only confirm that cloning a new repository doesn´t work. But meanwhile i know why. When there is a space in the path to SparkleShare.exe cloning a repository will fail.
I suppose you installed it in the default location `c:\Program Files (x86)\SparkleShare` ? If so please uninstall it and install it in a path without spaces (e.g `c:\SparkleShare`). You can select this in the Destination Folder Pane of the installer. Then you should have the full functionality. 
Can you please check and confirm? After that i will fix the "space issue" and create an new ci release which can handle spaces in the path.

**Comment by BinyaminPekar** [comment] 2021-10-03 10:42
You were absolutely correct. Installing directly into `C:\` allowed me to clone. Thank you for your fork. Once you fix this issue - I'll probably start using it in production.

Have a nice day!

**Comment by AvtechScientific** [comment] 2021-10-11 06:35
Anything new on this?

**Comment by uenz** [comment] 2021-10-11 06:43
The windows version is fixed, but the ci build chain for os x has some errors. I first wanted to fix this before the next build. If it takes to much time, i remove os x from the ci. This week the fixed windows version will be ready.

**Comment by AvtechScientific** [comment] 2021-10-11 06:45
Do you want me to take a look on the Linux build? Can you post here what is the error message there?

**Comment by AvtechScientific** [comment] 2021-10-11 06:46
Or even better link on the CI error message so I can see it myself in the real process...

**Comment by uenz** [comment] 2021-10-11 06:47
There is no error, it builds just fine. But the script which should create the tar.gz does not work, because the files are not in the place the script searches it.

**Comment by AvtechScientific** [comment] 2021-10-11 06:52
> There is no error, it builds just fine. But the script which should create the tar.gz does not work, because the files are not in the place the script searches it.

So maybe we can either change the script to look in the place where the build artifacts currently are, or place the artifacts in the directory where the script expects them...

Can you, please, point on the script and the artifacts location?

**Comment by uenz** [comment] 2021-10-11 06:56
If you want to take a look, its easiest to do the linux steps in [travis.yaml](https://github.com/uenz/SparkleShare/blob/feature/WindowsTravisCi/.travis.yml) on a local pc. The CI logfiles arent really helpfull and debugging with the CI is extremely time consuming. I switched to do all the debugging of the process locally and then try the locally working commands on the CI.
I think there is no need to use docker in the CI, but this is the "original" setup. At the moment i work on this [branch](https://github.com/uenz/SparkleShare/tree/feature/WindowsTravisCi).
I think the .yaml is the best documentation of the build steps and file location.

**Comment by uenz** [comment] 2021-10-12 21:15
Hi, just ceated a new release, which works fine for me. If someone tries it, please give feedback here.
There is still an issue in the mac build process, therefore i only build a windows version.

**Comment by AvtechScientific** [comment] 2021-10-13 06:34
@uenz - thank you very much! May I ask you to also merge this recent small [translation PR](https://github.com/hbons/SparkleShare/pull/1977), please, so I can test both (and so there is less merge work for @hbons at the end).

Thank you again!

**Comment by AvtechScientific** [comment] 2021-10-13 06:37
Also, please, post the link to the `.msi` file to test...

**Comment by uenz** [comment] 2021-10-13 14:40
[Here](https://github.com/uenz/SparkleShare/releases/download/CI-Build2/SparkleShare-windows-nightly.msi) is the Link to the latest setup file. The last merges which @hbons accepted were only small changes on one file. So changes to get it in the original sources are higher as single request.
But i can integrate it here also.
I have no idea how i can grab just the file...

**Comment by AvtechScientific** [comment] 2021-10-13 15:32
I think you just checkout `feature/WindowsTravisCi` branch and then just `git pull https://github.com/BinyaminPekar/SparkleShare.git` or am I wrong?

**Comment by uenz** [comment] 2021-10-13 17:54
@AvtechScientific Thanks for the git lesson, it worked! The next build will be with the updated language file.

**Comment by AvtechScientific** [comment] 2021-10-13 18:32
Great, let me know, once you have it and don't forget to post the link on the `.msi` file. Thank you!

**Comment by AvtechScientific** [comment] 2021-10-15 05:33
@uenz - any news on the new windows build (with the updated language file)?

**Comment by uenz** [comment] 2021-10-15 19:54
Unfortunately i found another bug related to spaces in pathes, which i cant solve at the moment. 
But the impact is small: the windows user folder must not contain spaces
Here is an new [installer](https://github.com/uenz/SparkleShare/releases/tag/CI-Build) for further testing.
See the known bugs in above link.

**Comment by AvtechScientific** [comment] 2021-10-16 20:25
No hurry... fix the bugs, once you have time... then let me know and I'll test it. Thank you!

**Comment by AvtechScientific** [comment] 2021-10-19 07:06
@uenz - what do you mean by "is not possible to use encrypted repos"? You can't use SSH keys to access repos or something else?

**Comment by uenz** [comment] 2021-10-19 18:51
No, ssh connections and key handling work fine. 
When clonig a new bare repo SparkleShare asks if you want to encrypt the files on the server. See [here](https://golb.hplar.ch/2018/06/self-hosted-gdrive-onedrive-dropbox-alternative.html) under client side encryption. That this works the command openssl.exe is needed. This is not the "normal" usecase. I found a solution that the encryption also works, but i'll do a bit more testing before next build.

**Comment by uenz** [comment] 2021-10-23 14:06
Im happy to announce the ReleaseCandidate 1 of the windows version [here](https://github.com/uenz/SparkleShare/releases/tag/3.28%2B). 
The updated language pack is included. All knows bugs are fixed. Only restriction is that the user folder name must not contain spaces.
Please test and give feedback. If no other bugs occure, ill merge the changes back to my pull request @hbons.

**Comment by AvtechScientific** [comment] 2021-10-24 12:16
@uenz - thank you very much for the update!

I have tested the RC1 version you have provided and it worked really well:
1. It fixes the old unicode issue hbons#1753
2. There are no problems with cloning repositories, even if SparkleShare is installed into a directory containing spaces in its name.

There is one thing that I've noticed which is different from the current official Windows version, however I can't call it a bug: once you clone a new project - then inside SparkleShare a new directory is created with the domain name of the host (in my case it was github.com), and the clone is put inside that directory. In the current version the clone was placed directly into the SparkleShare directory... Is this the expected behavior?

**Comment by uenz** [comment] 2021-10-24 19:21
@AvtechScientific  I also installed the version from the GitHub repo, but my repos are in a subfolder wich is named like the server. So I can’t confirm that behaviour and it is definitively not intended.

**Comment by AvtechScientific** [comment] 2021-10-24 19:33
@uenz - try to clone some arbitrary repo from GitHub (and maybe GitLab - I didn't check it though) to see whether you observe this behavior...

**Comment by uenz** [comment] 2021-10-25 08:03
@AvtechScientific When i clone a repo it resides where i expect it. Tried it with Github: \SparkleShare\github.com\tartool
Did you click on the Github Server Icon and then added the remote path or did you type all?
The pathname will be created in `DetermineFolderPath` in the file BaseController.cs. It will be generated from the RemoteURL. So if clonig works, the RemoteURL should be ok and resolve to a server / reponame structure.

**Comment by AvtechScientific** [comment] 2021-10-25 08:07
I didn't click the "Github Server" icon during cloning but rather "My own server", however nevertheless I did clone my fork of SparkleShare from GitHub and it landed at: `\SparkleShare\github.com\SparkleShare`.
Ok, so it looks like it is intended behavior... I think the current version would clone it to `\SparkleShare\SparkleShare`, but it doesn't really matter...

**Comment by uenz** [comment] 2021-10-25 09:15
@AvtechScientific If you mean the Version 1.4 as the current versiont, then you are rigth. The sparkleshare teams made this changes on the way to 2.x releases.

**Comment by AvtechScientific** [comment] 2021-10-25 09:49
Yes, that's what I meant... If so - everything is great and you can merge! Thank you very much. I hope @hbons will merge it upstream as well soon...

**Comment by uenz** [comment] 2021-11-02 19:01
This [RC1](https://github.com/uenz/SparkleShare/releases/tag/3.28%2B) build solves all mentioned issues.

**Closed as completed** 2021-11-02 19:01 UTC
